baseURL = 'https://nanwang.art/'
languageCode = 'en-us'
title = 'Nan Wang'
theme = 'modern-blog'

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = 'NanWang.Art'
  description = ''
  keywords = 'design,life,personal blog'

